<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from standaloneusers/xml/schema/CRM/Standaloneusers/Role.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:b027d757eff8ad3b630c304037699382)
 */

/**
 * Placeholder class retained for legacy compatibility.
 */
class CRM_Standaloneusers_DAO_Role extends CRM_Core_DAO_Base {
}
