<?php
use CRM_AfformAdmin_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Afform_Admin',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Afform_Admin',
        'label' => E::ts('Afforms'),
        'api_entity' => 'Afform',
        'api_params' => [
          'version' => 4,
          'select' => [
            'title',
            'name',
            'type',
            'server_route',
            'is_public',
            'placement:label',
            'placement:icon',
            'submit_enabled',
            'submit_limit',
            'submission_count',
            'submission_date',
            'submit_currently_open',
            'has_local',
            'has_base',
            'base_module:label',
            'tags:label',
            'entity_type',
          ],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Afform_Admin_SearchDisplay_Afform_Blocks_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Afform_Blocks_Table',
        'label' => E::ts('Field Blocks Table'),
        'saved_search_id.name' => 'Afform_Admin',
        'type' => 'table',
        'settings' => [
          'actions' => FALSE,
          'limit' => 50,
          'classes' => ['table', 'table-striped'],
          'pager' => [
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'placeholder' => 5,
          'sort' => [
            ['title', 'ASC'],
          ],
          'noResultsText' => 'Clear the above filters to see all forms.',
          'columns' => [
            [
              'type' => 'html',
              'key' => 'title',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
              'rewrite' => '<strong>{$title|escape}</strong><div class="help-block">{$name|escape}</div>',
            ],
            [
              'type' => 'field',
              'key' => 'entity_type',
              'label' => E::ts('Block Entity'),
              'sortable' => TRUE,
            ],
            [
              'path' => '~/afAdmin/afListPlacementColumn.html',
              'type' => 'include',
              'label' => E::ts('Placement'),
            ],
            [
              'type' => 'field',
              'key' => 'base_module:label',
              'label' => E::ts('Package'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'tags:label',
              'label' => E::ts('Tags'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/admin/afform#/edit/[name]',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'primary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/admin/afform#/clone/[name]',
                  'icon' => 'fa-files-o',
                  'text' => E::ts('Clone'),
                  'style' => 'secondary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'task' => 'revert',
                  'entity' => 'Afform',
                  'icon' => 'fa-undo',
                  'text' => E::ts('Revert'),
                  'style' => 'warning',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Afform',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'columnMode' => 'custom',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Afform_Admin_SearchDisplay_Afform_Forms_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Afform_Forms_Table',
        'label' => E::ts('Submission Forms Table'),
        'saved_search_id.name' => 'Afform_Admin',
        'type' => 'table',
        'settings' => [
          'actions' => FALSE,
          'limit' => 50,
          'classes' => ['table', 'table-striped'],
          'pager' => [
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'placeholder' => 5,
          'sort' => [
            ['title', 'ASC'],
          ],
          'noResultsText' => 'Clear the above filters to see all forms.',
          'columns' => [
            [
              'type' => 'html',
              'key' => 'title',
              'label' => E::ts('Title'),
              'title' => NULL,
              'sortable' => TRUE,
              'rewrite' => '<strong>{$title|escape}</strong><div class="help-block">{$name|escape}</div>',
            ],
            [
              'path' => '~/afAdmin/afListPlacementColumn.html',
              'type' => 'include',
              'label' => E::ts('Placement'),
            ],
            [
              'type' => 'html',
              'key' => 'submit_currently_open',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
              'rewrite' => '{if $submit_currently_open}🟢 {ts escape=\'html\'}Open{/ts}{else}🔴 {ts escape=\'html\'}Closed{/ts}{/if}
{if $submit_limit && $submit_enabled}<div class="help-block">({ts 1=$submit_limit - $submission_count}%1 remaining{/ts})</div>{/if}',
            ],
            [
              'type' => 'html',
              'key' => 'submission_count',
              'label' => E::ts('Submissions'),
              'sortable' => TRUE,
              'rewrite' => '{if $submission_count}<a href="{crmURL p=\'civicrm/admin/afform/submissions?name=[name]\'}">{ts count=$submission_count plural=\'%count Submissions\' escape=\'html\'}1 Submission{/ts}</a>
<div class="help-block">{ts 1=$submission_date|crmDate:"shortdate" escape=\'html\'}Last submitted %1{/ts}</div>{/if}',
            ],
            [
              'type' => 'field',
              'key' => 'base_module:label',
              'label' => E::ts('Package'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'tags:label',
              'label' => E::ts('Tags'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/admin/afform#/edit/[name]',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'primary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/admin/afform#/clone/[name]',
                  'icon' => 'fa-files-o',
                  'text' => E::ts('Clone'),
                  'style' => 'secondary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'task' => 'revert',
                  'entity' => 'Afform',
                  'icon' => 'fa-undo',
                  'text' => E::ts('Revert'),
                  'style' => 'warning',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Afform',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'columnMode' => 'custom',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Afform_Admin_SearchDisplay_Afform_Searches_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Afform_Searches_Table',
        'label' => E::ts('Search Forms Table'),
        'saved_search_id.name' => 'Afform_Admin',
        'type' => 'table',
        'settings' => [
          'actions' => FALSE,
          'limit' => 50,
          'classes' => ['table', 'table-striped'],
          'pager' => [
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'placeholder' => 5,
          'sort' => [
            ['title', 'ASC'],
          ],
          'noResultsText' => 'Clear the above filters to see all forms.',
          'columns' => [
            [
              'type' => 'html',
              'key' => 'title',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
              'rewrite' => '<strong>{$title|escape}</strong><div class="help-block">{$name|escape}</div>',
            ],
            [
              'path' => '~/afAdmin/afListPlacementColumn.html',
              'type' => 'include',
              'label' => E::ts('Placement'),
            ],
            [
              'type' => 'field',
              'key' => 'base_module:label',
              'label' => E::ts('Package'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'tags:label',
              'label' => E::ts('Tags'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/admin/afform#/edit/[name]',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'primary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/admin/afform#/clone/[name]',
                  'icon' => 'fa-files-o',
                  'text' => E::ts('Clone'),
                  'style' => 'secondary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'task' => 'revert',
                  'entity' => 'Afform',
                  'icon' => 'fa-undo',
                  'text' => E::ts('Revert'),
                  'style' => 'warning',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Afform',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'columnMode' => 'custom',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Afform_Admin_SearchDisplay_Afform_System_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Afform_System_Table',
        'label' => E::ts('System Forms Table'),
        'saved_search_id.name' => 'Afform_Admin',
        'type' => 'table',
        'settings' => [
          'actions' => FALSE,
          'limit' => 50,
          'classes' => ['table', 'table-striped'],
          'pager' => [
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'placeholder' => 5,
          'sort' => [
            ['title', 'ASC'],
          ],
          'columns' => [
            [
              'type' => 'html',
              'key' => 'title',
              'label' => E::ts('Title'),
              'title' => NULL,
              'sortable' => TRUE,
              'rewrite' => '<strong>{$title|escape}</strong><div class="help-block">{$name|escape}</div>',
            ],
            [
              'type' => 'field',
              'key' => 'type:label',
              'label' => E::ts('Type'),
              'sortable' => TRUE,
            ],
            [
              'path' => '~/afAdmin/afListPlacementColumn.html',
              'type' => 'include',
              'label' => E::ts('Placement'),
            ],
            [
              'type' => 'html',
              'key' => 'submission_count',
              'label' => E::ts('Submissions'),
              'sortable' => TRUE,
              'rewrite' => '{if $submission_count}<a href="{crmURL p=\'civicrm/admin/afform/submissions?name=[name]\'}">{ts count=$submission_count plural=\'%count Submissions\' escape=\'html\'}1 Submission{/ts}</a>
<div class="help-block">{ts 1=$submission_date|crmDate:"shortdate" escape=\'html\'}Last submitted %1{/ts}</div>{/if}',
            ],
            [
              'type' => 'field',
              'key' => 'base_module:label',
              'label' => E::ts('Package'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'tags:label',
              'label' => E::ts('Tags'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/admin/afform#/edit/[name]',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'primary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'path' => 'civicrm/admin/afform#/clone/[name]',
                  'icon' => 'fa-files-o',
                  'text' => E::ts('Clone'),
                  'style' => 'secondary',
                  'size' => 'btn-xs',
                  'conditions' => [
                    ['type', '!=', 'system'],
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                ],
                [
                  'task' => 'revert',
                  'entity' => 'Afform',
                  'icon' => 'fa-undo',
                  'text' => E::ts('Revert'),
                  'style' => 'warning',
                  'size' => 'btn-xs',
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'columnMode' => 'custom',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
