#!/bin/bash

# Note: This shell script should be designed and tested for cross-platform use

set -e

if [ "$GIT_CANONICAL_REPO_NAME" = "civicrm-core" ]; then
  PACKAGES="$GIT_DIR/../packages"
else
  PACKAGES="$GIT_DIR/../../packages"
fi
