#!/usr/bin/env php
<?php
/* PHPUnit
 *
 * Copyright (c) 2002-2008, Sebastian Bergmann <sb@sebastian-bergmann.de>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Sebastian Bergmann nor the names of his
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRIC
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * $Id: phpunit 522 2012-04-23 13:53:45Z deepak $
 */

$GLOBALS['base_dir'] = dirname( dirname( dirname( __FILE__ ) ) );
$tools_pkgs_dir = $GLOBALS['base_dir'] . DIRECTORY_SEPARATOR . 'tools' . DIRECTORY_SEPARATOR . 'packages';
$tests_dir = $GLOBALS['base_dir']  . DIRECTORY_SEPARATOR . 'tests' . DIRECTORY_SEPARATOR . 'phpunit';
$civi_pkgs_dir = $GLOBALS['base_dir'] .   DIRECTORY_SEPARATOR . 'packages';
ini_set('safe_mode', 0);
ini_set('include_path',
        "{$GLOBALS['base_dir']}" . PATH_SEPARATOR .
        "$tools_pkgs_dir"       . PATH_SEPARATOR .
        "$tests_dir"            . PATH_SEPARATOR .
        "$civi_pkgs_dir"        . PATH_SEPARATOR
        . ini_get( 'include_path') );

#  Relying on system timezone setting produces a warning,
#  doing the following prevents the warning message
if ( file_exists( '/etc/timezone' ) ) {
    $timezone = trim( file_get_contents( '/etc/timezone' ) );
    if ( ini_set('date.timezone', $timezone ) === false ) {
        echo "ini_set( 'date.timezone', '$timezone' ) failed\n";
    }
}

# Crank up the memory
ini_set('memory_limit', '2G');

error_reporting( E_ALL );

require 'PHPUnit/TextUI/Command.php';

define('PHPUnit_MAIN_METHOD', 'PHPUnit_TextUI_Command::main');

require dirname(__FILE__) . DIRECTORY_SEPARATOR .
	'..' . DIRECTORY_SEPARATOR .
	'packages' . DIRECTORY_SEPARATOR .
	'PHPUnit' . DIRECTORY_SEPARATOR .
	'Autoload.php';

PHPUnit_TextUI_Command::main( );
