<?php

/**
 * Implements hook_menu
 */
function extdir_menu() {
  $items = array();
  $items['extdir/%'] = array(
    'page callback' => 'extdir_pages_listing',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'extdir.pages.inc',
  );
  $items['extdir/%/%'] = array(
    'page callback' => 'extdir_pages_xml',
    'page arguments' => array(1,2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'extdir.pages.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme
 */
function extdir_theme() {
  return array(
    'extdir_list' => array(
      'template' => 'extdir_list',
      'variables' => array('extensions' => NULL),
    ),
  );
}

/**
 * Implementation of hook_node_insert
 */
function extdir_node_insert($node) {
  switch ($node->type) {
    case 'extension':
    case 'extension_release_civicrm':
      _extdir_flush();
      break;
    default:
  }
}

/**
 * Implementation of hook_node_update
 */
function extdir_node_update($node) {
  switch ($node->type) {
    case 'extension':
    case 'extension_release_civicrm':
      _extdir_flush();
      break;
    default:
  }
}

function _extdir_flush() {
  db_query('DELETE FROM cache_page WHERE cid LIKE :cid', array(':cid' => '%/extdir/%'));
}