<?php
return [
  'test_key' => [
    'group_name' => 'Test Settings',
    'group' => 'test',
    'name' => 'test_key',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Test Key',
    'title' => 'Test Key',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ],
  'test_secret' => [
    'group_name' => 'Test Settings',
    'group' => 'test',
    'name' => 'test_secret',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Test Secret',
    'title' => 'Test Secret',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ],
  'test_public_certificate' => [
    'group_name' => 'Test Settings',
    'group' => 'test',
    'name' => 'test_public_certificate',
    'type' => 'Text',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Test Public Certificate Path',
    'description' => 'Enter the full path to your public Certificate',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'test_private_key' => [
    'group_name' => 'Test Settings',
    'group' => 'test',
    'name' => 'test_private_key',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Test Private Key Path',
    'description' => 'Enter the full path to your private Key',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ],
];
