<?php
// CRM-8150
return CRM_Core_CodeGen_SqlData::create('civicrm_action_mapping')
  ->addValues([
    [
      'entity' => 'civicrm_activity',
      'entity_value' => 'activity_type',
      'entity_value_label' => 'Activity Type',
      'entity_status' => 'activity_status',
      'entity_status_label' => 'Activity Status',
      'entity_date_start' => 'activity_date_time',
      'entity_date_end' => NULL,
      'entity_recipient' => 'activity_contacts',
    ],
    [
      'entity' => 'civicrm_participant',
      'entity_value' => 'event_type',
      'entity_value_label' => 'Event Type',
      'entity_status' => 'civicrm_participant_status_type',
      'entity_status_label' => 'Participant Status',
      'entity_date_start' => 'event_start_date',
      'entity_date_end' => 'event_end_date',
      'entity_recipient' => 'event_contacts',
    ],
    [
      'entity' => 'civicrm_participant',
      'entity_value' => 'civicrm_event',
      'entity_value_label' => 'Event Name',
      'entity_status' => 'civicrm_participant_status_type',
      'entity_status_label' => 'Participant Status',
      'entity_date_start' => 'event_start_date',
      'entity_date_end' => 'event_end_date',
      'entity_recipient' => 'event_contacts',
    ],
    [
      'entity' => 'civicrm_membership',
      'entity_value' => 'civicrm_membership_type',
      'entity_value_label' => 'Membership Type',
      'entity_status' => 'auto_renew_options',
      'entity_status_label' => 'Auto Renew Options',
      'entity_date_start' => 'membership_join_date',
      'entity_date_end' => 'membership_end_date',
      'entity_recipient' => NULL,
    ],
    [
      'entity' => 'civicrm_participant',
      'entity_value' => 'event_template',
      'entity_value_label' => 'Event Template',
      'entity_status' => 'civicrm_participant_status_type',
      'entity_status_label' => 'Participant Status',
      'entity_date_start' => 'event_start_date',
      'entity_date_end' => 'event_end_date',
      'entity_recipient' => 'event_contacts',
    ],
    [
      'entity' => 'civicrm_contact',
      'entity_value' => 'civicrm_contact',
      'entity_value_label' => 'Date Field',
      'entity_status' => 'contact_date_reminder_options',
      'entity_status_label' => 'Annual Options',
      'entity_date_start' => 'date_field',
      'entity_date_end' => NULL,
      'entity_recipient' => NULL,
    ],
  ]);
