<?php
/*
 +--------------------------------------------------------------------+
 | CiviCRM version 4.4                                                |
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC (c) 2004-2013                                |
 +--------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                    |
 |                                                                    |
 | CiviCRM is free software; you can copy, modify, and distribute it  |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
 |                                                                    |
 | CiviCRM is distributed in the hope that it will be useful, but     |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | You should have received a copy of the GNU Affero General Public   |
 | License and the CiviCRM Licensing Exception along                  |
 | with this program; if not, contact CiviCRM LLC                     |
 | at info[AT]civicrm[DOT]org. If you have questions about the        |
 | GNU Affero General Public License or the licensing of CiviCRM,     |
 | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
 +--------------------------------------------------------------------+
*/

/**
 *
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * Generated from xml/schema/CRM/Dedupe/Exception.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */

namespace Civi\Dedupe;

require_once 'Civi/Core/Entity.php';

use Doctrine\ORM\Mapping as ORM;
use Civi\API\Annotation as CiviAPI;
use JMS\Serializer\Annotation as JMS;

/**
 * Exception
 *
 * @CiviAPI\Entity("Exception")
 * @CiviAPI\Permission()
 * @ORM\Table(name="civicrm_dedupe_exception", uniqueConstraints={@ORM\UniqueConstraint(name="UI_contact_id1_contact_id2", columns={"contact_id1","contact_id2"})}, indexes={@ORM\Index(name="FK_civicrm_dedupe_exception_contact_id1", columns={"contact_id1"}),@ORM\Index(name="FK_civicrm_dedupe_exception_contact_id2", columns={"contact_id2"})})
 * @ORM\Entity
 *
 */
class Exception extends \Civi\Core\Entity {

  /**
   * @var integer
   *
   * @JMS\Type("integer")
   * @ORM\Column(name="id", type="integer", nullable=false, options={"unsigned":true} )
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="IDENTITY")
   */
  private $id;
    
  /**
   * @var \Civi\Contact\Contact
   *
   * 
   * @ORM\ManyToOne(targetEntity="Civi\Contact\Contact")
   * @ORM\JoinColumns({@ORM\JoinColumn(name="contact_id1", referencedColumnName="id", onDelete="CASCADE")})
   * 
   */
  private $contact1;
  
  /**
   * @var \Civi\Contact\Contact
   *
   * 
   * @ORM\ManyToOne(targetEntity="Civi\Contact\Contact")
   * @ORM\JoinColumns({@ORM\JoinColumn(name="contact_id2", referencedColumnName="id", onDelete="CASCADE")})
   * 
   */
  private $contact2;

  /**
   * Get id
   *
   * @return integer
   */
  public function getId() {
    return $this->id;
  }
    
  /**
   * Set contact1
   *
   * @param \Civi\Contact\Contact $contact1
   * @return Exception
   */
  public function setContact1(\Civi\Contact\Contact $contact1 = null) {
    $this->contact1 = $contact1;
    return $this;
  }

  /**
   * Get contact1
   *
   * @return \Civi\Contact\Contact
   */
  public function getContact1() {
    return $this->contact1;
  }
  
  /**
   * Set contact2
   *
   * @param \Civi\Contact\Contact $contact2
   * @return Exception
   */
  public function setContact2(\Civi\Contact\Contact $contact2 = null) {
    $this->contact2 = $contact2;
    return $this;
  }

  /**
   * Get contact2
   *
   * @return \Civi\Contact\Contact
   */
  public function getContact2() {
    return $this->contact2;
  }

  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  public static $_fields = NULL;

  static function &fields( ) {
    if ( !self::$_fields) {
      self::$_fields = array (
      
              'id' => array(
      
        'name' => 'id',
        'propertyName' => 'id',
        'type' => \CRM_Utils_Type::T_INT,
                        'required' => true,
                                             
                                    
                          ),
      
              'contact_id1' => array(
      
        'name' => 'contact_id1',
        'propertyName' => 'contact1',
        'type' => \CRM_Utils_Type::T_INT,
                'title' => ts('First Dupe Contact ID'),
                                                     
                                    
                'FKClassName' => 'Civi_Contact_Contact',
                          ),
      
              'contact_id2' => array(
      
        'name' => 'contact_id2',
        'propertyName' => 'contact2',
        'type' => \CRM_Utils_Type::T_INT,
                'title' => ts('Second Dupe Contact ID'),
                                                     
                                    
                'FKClassName' => 'Civi_Contact_Contact',
                          ),
             );
    }
    return self::$_fields;
  }

}

