<?php
return [
  [
    'name' => 'SavedSearch_CORS_rules',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CORS_rules',
        'label' => 'CORS rules',
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'CorsRule',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'priority',
            'path',
            'origins',
            'headers',
            'methods',
            'max_age',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_CORS_rules_SearchDisplay_CORS_rules_table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CORS_rules_table',
        'label' => 'CORS rules table',
        'saved_search_id.name' => 'CORS_rules',
        'type' => 'table',
        'settings' => [
          'actions' => FALSE,
          'limit' => 50,
          'classes' => [
            'table',
            'table-striped',
          ],
          'pager' => [
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'placeholder' => 5,
          'sort' => [
            [
              'priority',
              'DESC',
            ],
            [
              'path',
              'ASC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => 'id',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'priority',
              'dataType' => 'Integer',
              'label' => 'Priority',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'path',
              'dataType' => 'String',
              'label' => 'Path',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'origins',
              'dataType' => 'String',
              'label' => 'Origins',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'headers',
              'dataType' => 'String',
              'label' => 'Headers',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'methods',
              'dataType' => 'String',
              'label' => 'Methods',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'max_age',
              'dataType' => 'Integer',
              'label' => 'Max age',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
          ],
          'addButton' => [
            'path' => 'civicrm/',
            'text' => 'Add Cors Rule',
            'icon' => 'fa-plus',
          ],
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
