#!/usr/bin/env /bin/bash

source `dirname $0`/demo.conf

pushd .

# load fromm joomla pristine
if [ $JOOMLA_DEMO_DBNAME ]; then
  if [ -f $JOOMLA_DEMO_PRISTINE ]; then
    mysqladmin -f drop $JOOMLA_DEMO_DBNAME
    echo "Creating civicrm-joomla-demo db.."
    mysqladmin create $JOOMLA_DEMO_DBNAME
    echo "Reloading civicrm-joomla-demo from pristine.."
    mysql $JOOMLA_DEMO_DBNAME < $JOOMLA_DEMO_PRISTINE
  fi
fi

popd
