#!/usr/bin/env /bin/bash

source `dirname $0`/demo.conf

pushd .

# creating wordpress pristine
if [ $WORDPRESS_DEMO_DBNAME ]; then
  if [ -f $WORDPRESS_DEMO_PRISTINE ]; then
    echo "Taking civicrm-wordpress-demo db dump.."
    mysqldump $WORDPRESS_DEMO_DBNAME > $TMP_DUMP_FILE
    echo "Creating civicrm-wordpress-demo pristine from dump.."
    cp $TMP_DUMP_FILE $WORDPRESS_DEMO_PRISTINE
  fi
fi

popd
