<?php
use CRM_CivicrmSearchUi_ExtensionUtil as E;

return [
    [
      'name' => 'SavedSearch_Find_participant',
      'entity' => 'SavedSearch',
      'cleanup' => 'always',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Find_participant',
          'label' => E::ts('Find participant'),
          'api_entity' => 'Participant',
          'api_params' => [
            'version' => 4,
            'select' => [
              'contact_id.sort_name',
              'event_id.title',
              'fee_level',
              'fee_amount',
              'register_date',
              'Participant_Event_event_id_01.start_date',
              'Participant_Event_event_id_01.end_date',
              'status_id:label',
              'role_id:label',
              'id',
            ],
            'orderBy' => [],
            'where' => [],
            'groupBy' => [],
            'join' => [
              [
                'Event AS Participant_Event_event_id_01',
                'INNER',
                [
                  'event_id',
                  '=',
                  'Participant_Event_event_id_01.id',
                ],
              ],
              [
                'Contact AS Participant_Contact_contact_id_01',
                'LEFT',
                [
                  'contact_id',
                  '=',
                  'Participant_Contact_contact_id_01.id',
                ],
              ],
            ],
            'having' => [],
          ],
        ],
        'match' => [
          'name',
        ],
      ],
    ],
    [
      'name' => 'SavedSearch_Find_participant_SearchDisplay_Find_participant_Table_1',
      'entity' => 'SearchDisplay',
      'cleanup' => 'always',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Find_participant_Table_1',
          'label' => E::ts('Find participant Table 1'),
          'saved_search_id.name' => 'Find_participant',
          'type' => 'table',
          'settings' => [
            'description' => NULL,
            'sort' => [
              [
                'register_date',
                'DESC',
              ],
            ],
            'limit' => 50,
            'pager' => [
              'expose_limit' => TRUE,
              'show_count' => TRUE,
              'hide_single' => TRUE,
            ],
            'placeholder' => 5,
            'columns' => [
              [
                'type' => 'field',
                'key' => 'contact_id.sort_name',
                'dataType' => 'String',
                'label' => E::ts('Participant'),
                'sortable' => TRUE,
                'link' => [
                  'path' => '',
                  'entity' => 'Contact',
                  'action' => 'view',
                  'join' => 'contact_id',
                  'target' => '_blank',
                ],
                'title' => E::ts('View Contact'),
              ],
              [
                'type' => 'field',
                'key' => 'event_id.title',
                'dataType' => 'String',
                'label' => E::ts('Event'),
                'sortable' => TRUE,
                'link' => [
                  'path' => '',
                  'entity' => 'Event',
                  'action' => 'view',
                  'join' => 'event_id',
                  'target' => 'crm-popup',
                ],
                'title' => E::ts('View Event'),
              ],
              [
                'type' => 'field',
                'key' => 'fee_level',
                'dataType' => 'Text',
                'label' => E::ts('Fee level'),
                'sortable' => TRUE,
              ],
              [
                'type' => 'field',
                'key' => 'fee_amount',
                'dataType' => 'Money',
                'label' => E::ts('Amount'),
                'sortable' => TRUE,
                'alignment' => 'text-right',
              ],
              [
                'type' => 'field',
                'key' => 'register_date',
                'dataType' => 'Timestamp',
                'label' => E::ts('Registered'),
                'sortable' => TRUE,
              ],
              [
                'type' => 'field',
                'key' => 'Participant_Event_event_id_01.start_date',
                'dataType' => 'Timestamp',
                'label' => E::ts('Event Date(s)'),
                'sortable' => TRUE,
                'rewrite' => '[Participant_Event_event_id_01.start_date] -  [Participant_Event_event_id_01.end_date]',
              ],
              [
                'type' => 'field',
                'key' => 'status_id:label',
                'dataType' => 'Integer',
                'label' => E::ts('Status'),
                'sortable' => TRUE,
                'alignment' => 'text-center',
              ],
              [
                'type' => 'field',
                'key' => 'role_id:label',
                'dataType' => 'String',
                'label' => E::ts('Role'),
                'sortable' => TRUE,
                'alignment' => 'text-center',
                'title' => NULL,
              ],
              [
                'text' => '',
                'style' => 'default',
                'size' => 'btn-xs',
                'icon' => 'fa-bars',
                'links' => [
                  [
                    'entity' => 'Participant',
                    'action' => 'view',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-eye',
                    'text' => E::ts('View Participant'),
                    'style' => 'default',
                    'path' => '',
                    'task' => '',
                    'condition' => [],
                  ],
                  [
                    'entity' => 'Participant',
                    'action' => 'update',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-pencil',
                    'text' => E::ts('Update Participant'),
                    'style' => 'default',
                    'path' => '',
                    'task' => '',
                    'condition' => [],
                  ],
                  [
                    'entity' => 'Participant',
                    'action' => 'delete',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-trash',
                    'text' => E::ts('Delete Participant'),
                    'style' => 'danger',
                    'path' => '',
                    'task' => '',
                    'condition' => [],
                  ],
                  [
                    'path' => 'civicrm/event/selfsvcupdate?reset=1&pid=[id]',
                    'icon' => 'fa-arrows-h',
                    'text' => E::ts('Transfer or cancel'),
                    'style' => 'default',
                    'condition' => [],
                    'task' => '',
                    'entity' => '',
                    'action' => '',
                    'join' => '',
                    'target' => 'crm-popup',
                  ],
                ],
                'type' => 'menu',
                'alignment' => 'text-right',
              ],
            ],
            'actions' => TRUE,
            'classes' => [
              'table',
              'table-striped',
            ],
            'headerCount' => TRUE,
            'button' => NULL,
          ],
        ],
        'match' => [
          'saved_search_id',
          'name',
        ],
      ],
    ],
];
