<?php
return CRM_Core_CodeGen_OptionGroup::create('account_relationship', 'a/0061')
  ->addMetadata([
    'title' => ts('Account Relationship'),
  ])
  ->addValues([
    [
      'label' => ts('Income Account is'),
      'value' => 1,
      'name' => 'Income Account is',
      'is_default' => 1,
      'description' => 'Income Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Credit/Contra Revenue Account is'),
      'value' => 2,
      'name' => 'Credit/Contra Revenue Account is',
      'description' => 'Credit/Contra Revenue Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Accounts Receivable Account is'),
      'value' => 3,
      'name' => 'Accounts Receivable Account is',
      'description' => 'Accounts Receivable Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Credit Liability Account is'),
      'value' => 4,
      'name' => 'Credit Liability Account is',
      'description' => 'Credit Liability Account is',
      'is_reserved' => 1,
      'is_active' => 0,
      'component_id' => 2,
    ],
    [
      'label' => ts('Expense Account is'),
      'value' => 5,
      'name' => 'Expense Account is',
      'description' => 'Expense Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Asset Account is'),
      'value' => 6,
      'name' => 'Asset Account is',
      'description' => 'Asset Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Cost of Sales Account is'),
      'value' => 7,
      'name' => 'Cost of Sales Account is',
      'description' => 'Cost of Sales Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Premiums Inventory Account is'),
      'value' => 8,
      'name' => 'Premiums Inventory Account is',
      'description' => 'Premiums Inventory Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Discounts Account is'),
      'value' => 9,
      'name' => 'Discounts Account is',
      'description' => 'Discounts Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Sales Tax Account is'),
      'value' => 10,
      'name' => 'Sales Tax Account is',
      'description' => 'Sales Tax Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Chargeback Account is'),
      'value' => 11,
      'name' => 'Chargeback Account is',
      'description' => 'Chargeback Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
    [
      'label' => ts('Deferred Revenue Account is'),
      'value' => 12,
      'name' => 'Deferred Revenue Account is',
      'description' => 'Deferred Revenue Account is',
      'is_reserved' => 1,
      'component_id' => 2,
    ],
  ]);
