<?php
return [
  [
    'name' => 'OptionGroup_grant_type',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'grant_type',
        'title' => 'Grant Type',
        'description' => NULL,
        'data_type' => NULL,
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'is_locked' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_type_OptionValue_Emergency',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_type',
        'label' => 'Emergency',
        'value' => '1',
        'name' => 'Emergency',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => TRUE,
        'weight' => 1,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'visibility_id' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_type_OptionValue_Family Support',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_type',
        'label' => 'Family Support',
        'value' => '2',
        'name' => 'Family Support',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 2,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'visibility_id' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_type_OptionValue_General Protection',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_type',
        'label' => 'General Protection',
        'value' => '3',
        'name' => 'General Protection',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 3,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'visibility_id' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_type_OptionValue_Impunity',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_type',
        'label' => 'Impunity',
        'value' => '4',
        'name' => 'Impunity',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 4,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'visibility_id' => NULL,
        'domain_id' => 'current_domain',
      ],
    ],
  ],
];
