<?php
return [
  [
    'name' => 'OptionGroup_grant_status',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'grant_status',
        'title' => 'Grant status',
        'description' => NULL,
        'data_type' => NULL,
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'is_locked' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Submitted',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Submitted',
        'value' => '1',
        'name' => 'Submitted',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => TRUE,
        'weight' => 1,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Eligible',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Eligible',
        'value' => '2',
        'name' => 'Eligible',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 2,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Ineligible',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Ineligible',
        'value' => '3',
        'name' => 'Ineligible',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 3,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Paid',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Paid',
        'value' => '4',
        'name' => 'Paid',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 4,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Awaiting Information',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Awaiting Information',
        'value' => '5',
        'name' => 'Awaiting Information',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 5,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Withdrawn',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Withdrawn',
        'value' => '6',
        'name' => 'Withdrawn',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 6,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_grant_status_OptionValue_Approved for Payment',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'grant_status',
        'label' => 'Approved for Payment',
        'value' => '7',
        'name' => 'Approved for Payment',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 7,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
];
