<?php
use CRM_Grant_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_CiviGrant_Dashboard_Chart',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CiviGrant_Dashboard_Chart',
        'label' => E::ts('CiviGrant Dashboard Chart'),
        'api_entity' => 'Grant',
        'api_params' => [
          'version' => 4,
          'select' => [
            'status_id:label',
            'COUNT(id) AS COUNT_id',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => ['status_id'],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_CiviGrant_Dashboard_Chart_SearchDisplay_CiviGrant_Dashboard_Status_Chart',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CiviGrant_Dashboard_Status_Chart',
        'label' => E::ts('CiviGrant Dashboard Status Chart'),
        'saved_search_id.name' => 'CiviGrant_Dashboard_Chart',
        'type' => 'chart-kit',
        'settings' => [
          'columns' => [
            [
              'axis' => 'x',
              'key' => 'status_id:label',
              'index' => 0,
              'name' => 'x_0',
              'label' => E::ts('Grant Status'),
              'sourceDataType' => 'Option',
              'scaleType' => 'categorical',
              'datePrecision' => NULL,
              'reduceType' => 'list',
              'seriesType' => NULL,
              'dataLabelType' => 'none',
              'dataLabelFormatter' => 'none',
            ],
            [
              'axis' => 'y',
              'key' => 'COUNT_id',
              'index' => 1,
              'name' => 'y_0',
              'scaleType' => 'numeric',
              'datePrecision' => NULL,
              'reduceType' => 'sum',
              'seriesType' => NULL,
              'dataLabelType' => 'title',
              'dataLabelFormatter' => 'none',
              'label' => E::ts('(Count) Grant ID'),
              'sourceDataType' => 'Integer',
              'dataLabelColumnPrefix' => FALSE,
            ],
            [
              'axis' => 'w',
              'key' => 'status_id:label',
              'index' => 2,
              'name' => 'w_0',
              'label' => E::ts('Grant Status'),
              'sourceDataType' => 'Option',
              'scaleType' => 'categorical',
              'datePrecision' => NULL,
              'reduceType' => 'list',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
            ],
          ],
          'format' => [
            'labelColor' => '#000000',
            'backgroundColor' => '#f2f2ed',
            'height' => 300,
            'width' => 500,
            'padding' => [
              'outer' => 10,
              'clip' => 20,
              'top' => 50,
              'bottom' => 50,
              'left' => 50,
              'right' => 50,
            ],
            'title' => E::ts('Grant Status'),
          ],
          'showLegend' => 'left',
          'maxSegments' => 8,
          'barWidth' => 10,
          'barGap' => 5,
          'chartType' => 'pie',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
