<?php
use CRM_BatchEntry_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contribution_Batch_Entry',
        'label' => E::ts('Contribution Batch'),
        'api_entity' => 'Contribution',
        'api_params' => [
          'version' => 4,
          'select' => [
            'contact_id',
            'total_amount',
            'fee_amount',
            'net_amount',
            'contribution_status_id:label',
            'financial_type_id:label',
            'receive_date',
            'source',
            'payment_instrument_id:label',
            'check_number',
            'invoice_number',
            'Contribution_ContributionSoft_contribution_id_01.soft_credit_type_id:label',
            'Contribution_ContributionSoft_contribution_id_01.contact_id',
            'Contribution_ContributionSoft_contribution_id_01.amount',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'ContributionSoft AS Contribution_ContributionSoft_contribution_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Contribution_ContributionSoft_contribution_id_01.contribution_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry_SearchDisplay_Contribution_Batch_Data_Entry_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contribution_Batch_Data_Entry_1',
        'label' => E::ts('Contribution Batch Data Entry'),
        'saved_search_id.name' => 'Contribution_Batch_Entry',
        'type' => 'batch',
        'settings' => [
          'classes' => [
            'table',
            'table-striped',
            'table-bordered',
            'crm-sticky-header',
          ],
          'limit' => 50,
          'pager' => [
            'hide_single' => TRUE,
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'contact_id',
              'label' => E::ts('Contact ID'),
              'spec' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
              ],
            ],
            [
              'type' => 'field',
              'key' => 'total_amount',
              'label' => E::ts('Total Amount'),
              'tally' => [
                'fn' => 'SUM',
              ],
              'spec' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'fee_amount',
              'label' => E::ts('Fee Amount'),
              'tally' => [
                'fn' => 'SUM',
              ],
              'spec' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'net_amount',
              'label' => E::ts('Net Amount'),
              'tally' => [
                'fn' => 'SUM',
              ],
              'spec' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_status_id:label',
              'label' => E::ts('Contribution Status'),
              'spec' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'label' => E::ts('Financial Type'),
              'spec' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
              ],
            ],
            [
              'type' => 'field',
              'key' => 'receive_date',
              'label' => E::ts('Contribution Date'),
              'spec' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'source',
              'label' => E::ts('Contribution Source'),
              'spec' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'payment_instrument_id:label',
              'label' => E::ts('Payment Method'),
              'spec' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'check_number',
              'label' => E::ts('Check Number'),
              'spec' => [
                'name' => 'check_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'check_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'invoice_number',
              'label' => E::ts('Invoice Number'),
              'spec' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Contribution_ContributionSoft_contribution_id_01.soft_credit_type_id:label',
              'label' => E::ts('Soft Credit Type'),
              'spec' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Contribution_ContributionSoft_contribution_id_01.contact_id',
              'label' => E::ts('Soft Credit Contact'),
              'spec' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Contribution_ContributionSoft_contribution_id_01.amount',
              'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Amount'),
              'spec' => [
                'name' => 'Contribution_ContributionSoft_contribution_id_01_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'amount',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => NULL,
                'serialize' => NULL,
                'entity_reference' => NULL,
              ],
            ],
          ],
          'tally' => [],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry_SearchDisplay_Contribution_Batch_Data_Entry_1_UserJob_1',
    'entity' => 'UserJob',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'status_id' => 2,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Contribution_Batch_Data_Entry_1',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_e653ef26609ffc9c2355db92522590be',
            'column_headers' => [
              'Contact ID',
              'Total Amount',
              'Fee Amount',
              'Net Amount',
              'Contribution Status',
              'Financial Type',
              'Contribution Date',
              'Contribution Source',
              'Payment Method',
              'Check Number',
              'Invoice Number',
              'Contribution Contribution Soft Credits: Soft Credit Type',
              'Contribution Contribution Soft Credits: Contact ID',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contact ID'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'fee_amount' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Fee Amount'),
              ],
              'net_amount' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Net Amount'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Status'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'label' => E::ts('Financial Type'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'check_number' => [
                'name' => 'check_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'check_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Check Number'),
              ],
              'invoice_number' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Invoice Number'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Type'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contribution Contribution Soft Credits: Contact ID'),
              ],
            ],
          ],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry_SearchDisplay_Contribution_Batch_Data_Entry_1_UserJob_2',
    'entity' => 'UserJob',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'end_date' => '2025-07-09 00:02:20',
        'status_id' => 1,
        'job_type' => 'search_batch_import',
        'queue_id.name' => 'user_job_44',
        'search_display_id.name' => 'Contribution_Batch_Data_Entry_1',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_8ca3e543ab5686273238f645766f3b18',
            'column_headers' => [
              'Contact ID',
              'Total Amount',
              'Fee Amount',
              'Net Amount',
              'Contribution Status',
              'Financial Type',
              'Contribution Date',
              'Contribution Source',
              'Payment Method',
              'Check Number',
              'Invoice Number',
              'Contribution Contribution Soft Credits: Soft Credit Type',
              'Contribution Contribution Soft Credits: Contact ID',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contact ID'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'fee_amount' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Fee Amount'),
              ],
              'net_amount' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Net Amount'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Status'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'label' => E::ts('Financial Type'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'check_number' => [
                'name' => 'check_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'check_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Check Number'),
              ],
              'invoice_number' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Invoice Number'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Type'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contribution Contribution Soft Credits: Contact ID'),
              ],
            ],
          ],
          'runner' => [
            'title' => E::ts('Queue Runner'),
            'onEndUrl' => '/civicrm/import/contact/summary?user_job_id=44&reset=1',
          ],
          'summary_info' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry_SearchDisplay_Contribution_Batch_Data_Entry_1_UserJob_3',
    'entity' => 'UserJob',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'end_date' => '2025-07-09 00:07:59',
        'status_id' => 1,
        'job_type' => 'search_batch_import',
        'queue_id.name' => 'user_job_45',
        'search_display_id.name' => 'Contribution_Batch_Data_Entry_1',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_a4c6ac0676a506a21c6809894b6d5f95',
            'column_headers' => [
              'Contact ID',
              'Total Amount',
              'Fee Amount',
              'Net Amount',
              'Contribution Status',
              'Financial Type',
              'Contribution Date',
              'Contribution Source',
              'Payment Method',
              'Check Number',
              'Invoice Number',
              'Soft Credit Type',
              'Soft Credit Contact',
              'Contribution Contribution Soft Credits: Soft Credit Amount',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contact ID'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'fee_amount' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Fee Amount'),
              ],
              'net_amount' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Net Amount'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Status'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'label' => E::ts('Financial Type'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'check_number' => [
                'name' => 'check_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'check_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Check Number'),
              ],
              'invoice_number' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Invoice Number'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Soft Credit Type'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Soft Credit Contact'),
              ],
              'Contribution_ContributionSoft_contribution_id_01_amount' => [
                'name' => 'Contribution_ContributionSoft_contribution_id_01_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'amount',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => NULL,
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Amount'),
              ],
            ],
          ],
          'runner' => [
            'title' => E::ts('Queue Runner'),
            'onEndUrl' => '/civicrm/import/contact/summary?user_job_id=45&reset=1',
          ],
          'summary_info' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry_SearchDisplay_Contribution_Batch_Data_Entry_1_UserJob_4',
    'entity' => 'UserJob',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'status_id' => 2,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Contribution_Batch_Data_Entry_1',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_6e76fda99d3eb00755580156655af25c',
            'column_headers' => [
              'Contact ID',
              'Total Amount',
              'Fee Amount',
              'Net Amount',
              'Contribution Status',
              'Financial Type',
              'Contribution Date',
              'Contribution Source',
              'Payment Method',
              'Check Number',
              'Invoice Number',
              'Soft Credit Type',
              'Soft Credit Contact',
              'Contribution Contribution Soft Credits: Soft Credit Amount',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contact ID'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'fee_amount' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Fee Amount'),
              ],
              'net_amount' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Net Amount'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Status'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'label' => E::ts('Financial Type'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'check_number' => [
                'name' => 'check_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'check_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Check Number'),
              ],
              'invoice_number' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Invoice Number'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Soft Credit Type'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Soft Credit Contact'),
              ],
              'Contribution_ContributionSoft_contribution_id_01_amount' => [
                'name' => 'Contribution_ContributionSoft_contribution_id_01_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'amount',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => NULL,
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Amount'),
              ],
            ],
          ],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contribution_Batch_Entry_SearchDisplay_Contribution_Batch_Data_Entry_1_UserJob_5',
    'entity' => 'UserJob',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'status_id' => 2,
        'job_type' => 'search_batch_import',
        'search_display_id.name' => 'Contribution_Batch_Data_Entry_1',
        'metadata' => [
          'DataSource' => [
            'table_name' => 'civicrm_tmp_d_searchbatch_a15be405b8c34a029dca36b67ee3b062',
            'column_headers' => [
              'Contact ID',
              'Total Amount',
              'Fee Amount',
              'Net Amount',
              'Contribution Status',
              'Financial Type',
              'Contribution Date',
              'Contribution Source',
              'Payment Method',
              'Check Number',
              'Invoice Number',
              'Soft Credit Type',
              'Soft Credit Contact',
              'Contribution Contribution Soft Credits: Soft Credit Amount',
            ],
            'column_specs' => [
              'contact_id' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Contact ID'),
              ],
              'total_amount' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Total Amount'),
              ],
              'fee_amount' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Fee Amount'),
              ],
              'net_amount' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Net Amount'),
              ],
              'contribution_status_id' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Status'),
              ],
              'financial_type_id' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'FinancialType',
                  'key' => 'id',
                ],
                'label' => E::ts('Financial Type'),
              ],
              'receive_date' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select Date',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Date'),
              ],
              'source' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Source'),
              ],
              'payment_instrument_id' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Payment Method'),
              ],
              'check_number' => [
                'name' => 'check_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'check_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Check Number'),
              ],
              'invoice_number' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
                'input_type' => 'Text',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Invoice Number'),
              ],
              'Contribution_ContributionSoft_contribution16b3265579af7863' => [
                'name' => 'Contribution_ContributionSoft_contribution16b3265579af7863',
                'data_type' => 'Integer',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'original_field_name' => 'soft_credit_type_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'Select',
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Soft Credit Type'),
              ],
              'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7' => [
                'name' => 'Contribution_ContributionSoft_contribution2fcfe8c2b6254fe7',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => 'EntityRef',
                'serialize' => NULL,
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
                'label' => E::ts('Soft Credit Contact'),
              ],
              'Contribution_ContributionSoft_contribution_id_01_amount' => [
                'name' => 'Contribution_ContributionSoft_contribution_id_01_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'original_field_name' => 'amount',
                'original_field_entity' => 'ContributionSoft',
                'input_type' => NULL,
                'serialize' => NULL,
                'entity_reference' => NULL,
                'label' => E::ts('Contribution Contribution Soft Credits: Soft Credit Amount'),
              ],
            ],
          ],
        ],
      ],
      'match' => ['name'],
    ],
  ],
];
