#!/bin/bash

. `dirname $0`/build-tarballs.conf

repo="$1"
rev="$2"
dryrun="$3"

# if this is not a tarball tagging commit, exit
[ $dryrun = dryrun ] || [ "`$svnlook -r $rev dirs-changed $repo | head -1`" = $tarball_branch ] || exit 0

# if this is not a tag add commit (e.g., it's a tag delete one), exit
[ $dryrun = dryrun ] || [ "`$svnlook -r $rev changed $repo | cut -d' ' -f1`" = A ] || exit 0

if [ $dryrun = dryrun ]; then
  version="`echo $repo | grep -o '[^/v]*$'`.$rev"
else
  version="`$svnlook -r $rev changed $repo | cut -d/ -f3`"
fi

workdir="$workdir"
mkdir -p $workdir/$version
cd $workdir/$version
mkdir -p php4 tarballs tmp

# when dryrunning, export the provided repo/rev, otherwise the tag
if [ $dryrun = dryrun ]; then
  $svn export $repo -r $rev export
else
  $svn export "$address""$tarball_branch""$version" export
fi

# create the distmaker.conf file
echo "
DM_SOURCEDIR=$workdir/$version/export
DM_GENFILESDIR=$workdir/$version/php4
DM_TMPDIR=$workdir/$version/tmp
DM_TARGETDIR=$workdir/$version/tarballs
DM_PHP=$php
DM_RSYNC=$rsync
DM_VERSION=$version
DM_REVISION=$rev
DM_ZIP=$zip
" > $workdir/$version/export/distmaker/distmaker.conf

# create a minimal civicrm.settings.php file
mkdir -p $workdir/$version/export/default
echo "<?php define('CIVICRM_GETTEXT_RESOURCEDIR', '$workdir/$version/export/l10n/'); define('CIVICRM_UF', 'Drupal'); global \$civicrm_root; \$civicrm_root = '$workdir/$version/export'; ?>" > $workdir/$version/export/default/civicrm.settings.php

# create a minimal settings_location.php file
echo "<?php define('CIVICRM_CONFDIR', '$workdir/$version/export'); ?>" > $workdir/$version/export/settings_location.php

# run the exported distmaker
cd $workdir/$version/export/distmaker
./distmaker.sh all > $workdir/$version/build.log

# exit here if it’s a dry run
[ $dryrun = dryrun ] && exit 0

# publish to sf.net
cd $workdir/$version/tarballs

$md5sum *.tar.gz *.zip > civicrm-$version.MD5SUMS
echo $gpg_pass | $gpg --armor --batch --passphrase-fd 0 --sign civicrm-$version.MD5SUMS

if [ "`echo -n $version | tr -d 0-9.`" = '' ]; then
  echo mkdir /home/frs/project/c/ci/civicrm/civicrm-stable/$version | $sftp civicrm,civicrm@frs.sf.net
  $rsync -aP --exclude='*starterkit.tgz' *.tar.gz *.zip *MD5SUMS* civicrm,civicrm@frs.sf.net:/home/frs/project/c/ci/civicrm/civicrm-stable/$version
else
  echo mkdir /home/frs/project/c/ci/civicrm/civicrm-latest/$version | $sftp civicrm,civicrm@frs.sf.net
  $rsync -aP --exclude='*starterkit.tgz' *.tar.gz *.zip *MD5SUMS* civicrm,civicrm@frs.sf.net:/home/frs/project/c/ci/civicrm/civicrm-latest/$version
fi

mv *.tar.gz *.zip *MD5SUMS* $build_dest

# cleanup
cd $workdir/$version
rm -r export php4 tmp tarballs tmp

# publish to latest.civicrm.org
if [ "`echo -n $version | tr -d 0-9.`" = '' ]; then
  echo $version > $latest/stable.txt
fi
echo $version > $latest/latest.txt
