<?php
return CRM_Core_CodeGen_OptionGroup::create('report_template', 'a/0039')
  ->addMetadata([
    'title' => ts('Report Template'),
  ])
  ->addValueTable(['label', 'name', 'value', 'weight', 'description'], [
    [ts('Constituent Report (Summary)'), 'CRM_Report_Form_Contact_Summary', 'contact/summary', 1, ts('Provides a list of address and telephone information for constituent records in your system.')],
    [ts('Constituent Report (Detail)'), 'CRM_Report_Form_Contact_Detail', 'contact/detail', 2, ts('Provides contact-related information on contributions, memberships, events and activities.')],
    [ts('Activity Details Report'), 'CRM_Report_Form_Activity', 'activity', 3, ts('Provides a list of constituent activity including activity statistics for one/all contacts during a given date range(required)')],
    [ts('Walk / Phone List Report'), 'CRM_Report_Form_Walklist_Walklist', 'walklist', 4, ts('Provides a detailed report for your walk/phonelist for targeted contacts'), 'is_active' => 0],
    [ts('Current Employer Report'), 'CRM_Report_Form_Contact_CurrentEmployer', 'contact/currentEmployer', 5, ts('Provides detail list of employer employee relationships along with employment details Ex Join Date')],
    [ts('Contribution Summary Report'), 'CRM_Report_Form_Contribute_Summary', 'contribute/summary', 6, ts('Groups and totals contributions by criteria including contact, time period, financial type, contributor location, etc.'), 'component_id' => 2],
    [ts('Contribution Detail Report'), 'CRM_Report_Form_Contribute_Detail', 'contribute/detail', 7, ts('Lists specific contributions by criteria including contact, time period, financial type, contributor location, etc. Contribution summary report points to this report for contribution details.'), 'component_id' => 2],
    [ts('Repeat Contributions Report'), 'CRM_Report_Form_Contribute_Repeat', 'contribute/repeat', 8, ts('Given two date ranges, shows contacts who contributed in both the date ranges with the amount contributed in each and the percentage increase / decrease.'), 'component_id' => 2],
    [ts('Contributions by Organization Report'), 'CRM_Report_Form_Contribute_OrganizationSummary', 'contribute/organizationSummary', 9, ts('Displays a detailed list of contributions grouped by organization, which includes contributions made by employees for the organisation.'), 'component_id' => 2],
    [ts('Contributions by Household Report'), 'CRM_Report_Form_Contribute_HouseholdSummary', 'contribute/householdSummary', 10, ts('Displays a detailed list of contributions grouped by household which includes contributions made by members of the household.'), 'component_id' => 2],
    [ts('Top Donors Report'), 'CRM_Report_Form_Contribute_TopDonor', 'contribute/topDonor', 11, ts('Provides a list of the top donors during a time period you define. You can include as many donors as you want (for example, top 100 of your donors).'), 'component_id' => 2],
    [ts('SYBUNT Report'), 'CRM_Report_Form_Contribute_Sybunt', 'contribute/sybunt', 12, ts('SYBUNT means some year(s) but not this year. Provides a list of constituents who donated at some time in the history of your organization but did not donate during the time period you specify.'), 'component_id' => 2],
    [ts('LYBUNT Report'), 'CRM_Report_Form_Contribute_Lybunt', 'contribute/lybunt', 13, ts('LYBUNT means last year but not this year. Provides a list of constituents who donated last year but did not donate during the time period you specify as the current year.'), 'component_id' => 2],
    [ts('Soft Credit Report'), 'CRM_Report_Form_Contribute_SoftCredit', 'contribute/softcredit', 14, ts('Shows contributions made by contacts that have been soft-credited to other contacts.'), 'component_id' => 2],
    [ts('Membership Report (Summary)'), 'CRM_Report_Form_Member_Summary', 'member/summary', 15, ts('Provides a summary of memberships by type and Member Since.'), 'component_id' => 3],
    [ts('Membership Report (Detail)'), 'CRM_Report_Form_Member_Detail', 'member/detail', 16, ts('Provides a list of members along with their membership status and membership details (Member Since, Membership Start Date, Membership Expiration Date). Can also display contributions (payments) associated with each membership.'), 'component_id' => 3],
    [ts('Membership Report (Lapsed)'), 'CRM_Report_Form_Member_Lapse', 'member/lapse', 17, ts('Provides a list of memberships that lapsed or will lapse before the date you specify.'), 'component_id' => 3],
    [ts('Event Participant Report (List)'), 'CRM_Report_Form_Event_ParticipantListing', 'event/participantListing', 18, ts('Provides lists of participants for an event.'), 'component_id' => 1],
    [ts('Event Income Report (Summary)'), 'CRM_Report_Form_Event_Summary', 'event/summary', 19, ts('Provides an overview of event income. You can include key information such as event ID, registration, attendance, and income generated to help you determine the success of an event.'), 'component_id' => 1],
    [ts('Event Income Report (Detail)'), 'CRM_Report_Form_Event_Income', 'event/income', 20, ts('Helps you to analyze the income generated by an event. The report can include details by participant type, status and payment method.'), 'component_id' => 1],
    [ts('Pledge Detail Report'), 'CRM_Report_Form_Pledge_Detail', 'pledge/detail', 21, ts('List of pledges including amount pledged, pledge status, next payment date, balance due, total amount paid etc.'), 'component_id' => 6],
    [ts('Pledged but not Paid Report'), 'CRM_Report_Form_Pledge_Pbnp', 'pledge/pbnp', 22, ts('Pledged but not Paid Report'), 'component_id' => 6],
    [ts('Relationship Report'), 'CRM_Report_Form_Contact_Relationship', 'contact/relationship', 23, ts('Relationship Report')],
    [ts('Case Summary Report'), 'CRM_Report_Form_Case_Summary', 'case/summary', 24, ts('Provides a summary of cases and their duration by date range, status, staff member and / or case role.'), 'component_id' => 7],
    [ts('Case Time Spent Report'), 'CRM_Report_Form_Case_TimeSpent', 'case/timespent', 25, ts('Aggregates time spent on case and / or non-case activities by activity type and contact.'), 'component_id' => 7],
    [ts('Contact Demographics Report'), 'CRM_Report_Form_Case_Demographics', 'case/demographics', 26, ts('Demographic breakdown for case clients (and or non-case contacts) in your database. Includes custom contact fields.'), 'component_id' => 7],
    [ts('Database Log Report'), 'CRM_Report_Form_Contact_Log', 'contact/log', 27, ts('Log of contact and activity records created or updated in a given date range.')],
    [ts('Activity Summary Report'), 'CRM_Report_Form_ActivitySummary', 'activitySummary', 28, ts('Shows activity statistics by type / date')],
    [ts('Bookkeeping Transactions Report'), 'CRM_Report_Form_Contribute_Bookkeeping', 'contribute/bookkeeping', 29, ts('Shows Bookkeeping Transactions Report'), 'component_id' => 2],
    [ts('Participant list Count Report'), 'CRM_Report_Form_Event_ParticipantListCount', 'event/participantlist', 31, ts('Shows the Participant list with Participant Count.'), 'component_id' => 1],
    [ts('Income Count Summary Report'), 'CRM_Report_Form_Event_IncomeCountSummary', 'event/incomesummary', 32, ts('Shows the Income Summary of events with Count.'), 'component_id' => 1],
    [ts('Case Detail Report'), 'CRM_Report_Form_Case_Detail', 'case/detail', 33, ts('Case Details'), 'component_id' => 7],
    [ts('Mail Bounce Report'), 'CRM_Report_Form_Mailing_Bounce', 'Mailing/bounce', 34, ts('Bounce Report for mailings'), 'component_id' => 4],
    [ts('Mail Summary Report'), 'CRM_Report_Form_Mailing_Summary', 'Mailing/summary', 35, ts('Summary statistics for mailings'), 'component_id' => 4],
    [ts('Mail Opened Report'), 'CRM_Report_Form_Mailing_Opened', 'Mailing/opened', 36, ts('Display contacts who opened emails from a mailing'), 'component_id' => 4],
    [ts('Mail Click-Through Report'), 'CRM_Report_Form_Mailing_Clicks', 'Mailing/clicks', 37, ts('Display clicks from each mailing'), 'component_id' => 4],
    [ts('Contact Logging Report (Summary)'), 'CRM_Report_Form_Contact_LoggingSummary', 'logging/contact/summary', 38, ts('Contact modification report for the logging infrastructure (summary).'), 'is_active' => 0],
    [ts('Contact Logging Report (Detail)'), 'CRM_Report_Form_Contact_LoggingDetail', 'logging/contact/detail', 39, ts('Contact modification report for the logging infrastructure (detail).'), 'is_active' => 0],
    [ts('Survey Report (Detail)'), 'CRM_Report_Form_Campaign_SurveyDetails', 'survey/detail', 43, ts('Detailed report for canvassing, phone-banking, walk lists or other surveys.'), 'component_id' => 9],
    [ts('Personal Campaign Page Report'), 'CRM_Report_Form_Contribute_PCP', 'contribute/pcp', 44, ts('Summarizes amount raised and number of contributors for each Personal Campaign Page.'), 'component_id' => 2],
    [ts('Pledge Summary Report'), 'CRM_Report_Form_Pledge_Summary', 'pledge/summary', 45, ts('Groups and totals pledges by criteria including contact, time period, pledge status, location, etc.'), 'component_id' => 6],
    [ts('Contribution Aggregate by Relationship'), 'CRM_Report_Form_Contribute_History', 'contribute/history', 46, ts('List contact\'s donation history, grouped by year, along with contributions attributed to any of the contact\'s related contacts.'), 'component_id' => 2],
    [ts('Mail Detail Report'), 'CRM_Report_Form_Mailing_Detail', 'mailing/detail', 47, ts('Provides reporting on Intended and Successful Deliveries, Unsubscribes and Opt-outs, Replies and Forwards.'), 'component_id' => 4],
    [ts('Contribution and Membership Details'), 'CRM_Report_Form_Member_ContributionDetail', 'member/contributionDetail', 48, ts('Contribution details for any type of contribution, plus associated membership information for contributions which are in payment for memberships.'), 'component_id' => 3],
    [ts('Recurring Contributions Report'), 'CRM_Report_Form_Contribute_Recur', 'contribute/recur', 49, ts('Provides information about the status of recurring contributions'), 'component_id' => 2],
    [ts('Recurring Contributions Summary'), 'CRM_Report_Form_Contribute_RecurSummary', 'contribute/recursummary', 49, ts('Provides simple summary for each payment instrument for which there are recurring contributions (e.g. Credit Card, Standing Order, Direct Debit, etc., NULL), showing within a given date range.'), 'component_id' => 2],
    [ts('Deferred Revenue Details'), 'CRM_Report_Form_Contribute_DeferredRevenue', 'contribute/deferredrevenue', 50, ts('Deferred Revenue Details Report'), 'component_id' => 2],
  ]);
