#membership search from smart builder created before 4.4
INSERT INTO `civicrm_mapping` (`id`, `name`, `description`, `mapping_type_id`) VALUES (554, NULL, NULL, NULL);
INSERT INTO `civicrm_mapping_field` (`id`, `mapping_id`, `name`, `contact_type`, `column_number`, `location_type_id`, `phone_type_id`, `im_provider_id`, `website_type_id`, `relationship_type_id`, `relationship_direction`, `grouping`, `operator`, `value`) VALUES (13338, 554, 'street_address', 'Individual', 0, NULL, NULL, NULL, NULL, NULL, NULL, 1, '', '');
INSERT INTO `civicrm_mapping_field` (`id`, `mapping_id`, `name`, `contact_type`, `column_number`, `location_type_id`, `phone_type_id`, `im_provider_id`, `website_type_id`, `relationship_type_id`, `relationship_direction`, `grouping`, `operator`, `value`) VALUES (13339, 554, 'state_province', 'Individual', 1, NULL, NULL, NULL, NULL, NULL, NULL, 1, '=', 'Maine');
INSERT INTO `civicrm_mapping_field` (`id`, `mapping_id`, `name`, `contact_type`, `column_number`, `location_type_id`, `phone_type_id`, `im_provider_id`, `website_type_id`, `relationship_type_id`, `relationship_direction`, `grouping`, `operator`, `value`) VALUES (13340, 554, 'membership_status', 'Membership', 2, NULL, NULL, NULL, NULL, NULL, NULL, 1, '=', 'Current');
INSERT INTO `civicrm_saved_search` (`id`, `form_values`, `mapping_id`, `search_custom_id`, `where_clause`, `select_tables`, `where_tables`) VALUES (794, 'a:8:{s:5:"qfKey";s:37:"a2a8452a4e966a5a8ec245264a5c4b5b_9671";s:6:"mapper";a:2:{i:1;a:3:{i:0;a:3:{i:0;s:10:"Individual";i:1;s:14:"street_address";i:2;s:1:" ";}i:1;a:3:{i:0;s:10:"Individual";i:1;s:14:"state_province";i:2;s:1:" ";}i:2;a:2:{i:0;s:10:"Membership";i:1;s:17:"membership_status";}}i:2;a:1:{i:0;a:1:{i:0;s:0:"";}}}s:8:"operator";a:2:{i:1;a:3:{i:0;s:7:"IS NULL";i:1;s:1:"=";i:2;s:1:"=";}i:2;a:1:{i:0;s:0:"";}}s:5:"value";a:2:{i:1;a:3:{i:0;s:0:"";i:1;s:5:"Maine";i:2;s:7:"Current";}i:2;a:1:{i:0;s:0:"";}}s:4:"task";s:2:"13";s:8:"radio_ts";s:6:"ts_all";s:11:"uf_group_id";s:0:"";s:14:"component_mode";i:1;}', 554, NULL, ' (  (  (civicrm_address.street_address IS NULL  ) AND civicrm_state_province.name IN (\'Maine\') AND LOWER(civicrm_membership_status.name) = \'current\' AND contact_a.contact_type IN (\'Individual\') )  ) ', 'a:13:{s:15:"civicrm_contact";i:1;s:15:"civicrm_address";i:1;s:22:"civicrm_state_province";i:1;s:15:"civicrm_country";i:1;s:13:"civicrm_email";i:1;s:13:"civicrm_phone";i:1;s:10:"civicrm_im";i:1;s:19:"civicrm_worldregion";i:1;s:18:"civicrm_membership";i:1;s:25:"civicrm_membership_status";i:1;s:6:"gender";i:1;s:17:"individual_prefix";i:1;s:17:"individual_suffix";i:1;}', 'a:5:{s:15:"civicrm_contact";i:1;s:15:"civicrm_address";i:1;s:22:"civicrm_state_province";i:1;s:18:"civicrm_membership";i:1;s:25:"civicrm_membership_status";i:1;}');
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (1854, 'Maine__Members_with_no_addre_1854', 'Maine - Members with no address', NULL, NULL, 794, 1, 'User and User Admin Only', ' ( `civicrm_group_contact_cache_1854`.group_id = 1854 ) ', 'a:12:{s:15:"civicrm_contact";i:1;s:15:"civicrm_address";i:1;s:22:"civicrm_state_province";i:1;s:15:"civicrm_country";i:1;s:13:"civicrm_email";i:1;s:13:"civicrm_phone";i:1;s:10:"civicrm_im";i:1;s:19:"civicrm_worldregion";i:1;s:34:"`civicrm_group_contact_cache_1854`";s:138:" LEFT JOIN civicrm_group_contact_cache `civicrm_group_contact_cache_1854` ON contact_a.id = `civicrm_group_contact_cache_1854`.contact_id ";s:6:"gender";i:1;s:17:"individual_prefix";i:1;s:17:"individual_suffix";i:1;}', 'a:2:{s:15:"civicrm_contact";i:1;s:34:"`civicrm_group_contact_cache_1854`";s:138:" LEFT JOIN civicrm_group_contact_cache `civicrm_group_contact_cache_1854` ON contact_a.id = `civicrm_group_contact_cache_1854`.contact_id ";}', '2', NULL, NULL, NULL, NULL, 0, 0, NULL, NULL);



