INSERT INTO civicrm_mapping (id,name,description,mapping_type_id) Values
(113, NULL, NULL, NULL);
INSERT INTO `civicrm_mapping_field` (`id`, `mapping_id`, `name`, `contact_type`, `column_number`, `location_type_id`, `phone_type_id`, `im_provider_id`, `relationship_type_id`, `relationship_direction`, `grouping`, `operator`, `value`, `website_type_id`) VALUES
(2841, 113, 'email', 'Individual', 0, NULL, NULL, NULL, NULL, NULL, 1, '', '', NULL),
(2842, 113, 'do_not_email', 'Individual', 1, NULL, NULL, NULL, NULL, NULL, 1, '!=', '1', NULL),
(2843, 113, 'is_opt_out', 'Individual', 2, NULL, NULL, NULL, NULL, NULL, 1, '!=', '1', NULL),
(2844, 113, 'first_name', 'Individual', 3, NULL, NULL, NULL, NULL, NULL, 1, '', '', NULL),
(2845, 113, 'state_province', 'Individual', 4, NULL, NULL, NULL, NULL, NULL, 1, '=', 'New York', NULL);
INSERT INTO `civicrm_saved_search` (`id`, `form_values`, `mapping_id`, `search_custom_id`) VALUES
(38, 'a:6:{s:6:"mapper";a:2:{i:1;a:5:{i:0;a:3:{i:0;s:10:"Individual";i:1;s:5:"email";i:2;s:1:" ";}i:1;a:2:{i:0;s:10:"Individual";i:1;s:12:"do_not_email";}i:2;a:2:{i:0;s:10:"Individual";i:1;s:10:"is_opt_out";}i:3;a:2:{i:0;s:10:"Individual";i:1;s:10:"first_name";}i:4;a:3:{i:0;s:10:"Individual";i:1;s:14:"state_province";i:2;s:1:" ";}}i:2;a:1:{i:0;a:1:{i:0;s:0:"";}}}s:8:"operator";a:2:{i:1;a:5:{i:0;s:11:"IS NOT NULL";i:1;s:2:"!=";i:2;s:2:"!=";i:3;s:11:"IS NOT NULL";i:4;s:1:"=";}i:2;a:1:{i:0;s:0:"";}}s:5:"value";a:2:{i:1;a:5:{i:0;s:0:"";i:1;s:1:"1";i:2;s:1:"1";i:3;s:0:"";i:4;s:8:"New York";}i:2;a:1:{i:0;s:0:"";}}s:4:"task";s:2:"13";s:8:"radio_ts";s:6:"ts_all";s:11:"uf_group_id";s:0:"";}', '113', NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`) VALUES (94, '_null_streets', '@ null streets', NULL, NULL, 38, 1, 'User and User Admin Only', ' ( `civicrm_group_contact_cache_242`.group_id = 94 ) ', 'a:10:{s:15:"civicrm_contact";i:1;s:15:"civicrm_address";i:1;s:22:"civicrm_state_province";i:1;s:15:"civicrm_country";i:1;s:13:"civicrm_email";i:1;s:13:"civicrm_phone";i:1;s:10:"civicrm_im";i:1;s:19:"civicrm_worldregion";i:1;s:33:"`civicrm_group_contact_cache_94`";s:136:" LEFT JOIN civicrm_group_contact_cache `civicrm_group_contact_cache_94` ON contact_a.id = `civicrm_group_contact_cache_94`.contact_id ";s:6:"gender";i:1;}', 'a:2:{s:15:"civicrm_contact";i:1;s:33:"`civicrm_group_contact_cache_94`";s:136:" LEFT JOIN civicrm_group_contact_cache `civicrm_group_contact_cache_94` ON contact_a.id = `civicrm_group_contact_cache_94`.contact_id ";}', NULL, NULL, NULL, NULL, NULL, 0, 0, NULL);
