<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Event_Templates',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Event_Templates',
        'label' => E::ts('Event Templates'),
        'api_entity' => 'Event',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'title',
            'event_type_id:label',
            'default_role_id:label',
            'participant_listing_id:label',
            'is_public',
            'is_monetary',
            'is_online_registration',
            'is_active',
            'template_title',
          ],
          'orderBy' => [],
          'where' => [
            [
              'is_template',
              '=',
              TRUE,
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Event_Templates_SearchDisplay_Event_Templates_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Event_Templates_Table_1',
        'label' => E::ts('Event Templates Table 1'),
        'saved_search_id.name' => 'Event_Templates',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            [
              'template_title',
              'ASC',
            ],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'template_title',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'event_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Event Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'default_role_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Participant Role'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'participant_listing_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Participant Listing'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_public',
              'dataType' => 'Boolean',
              'label' => E::ts('Public Event'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_monetary',
              'dataType' => 'Boolean',
              'label' => E::ts('Paid Event'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_online_registration',
              'dataType' => 'Boolean',
              'label' => E::ts('Allow Online Registration'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Is Active'),
              'sortable' => TRUE,
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'path' => 'civicrm/event/manage/settings?action=update&reset=1&id=[id]',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Event',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => [
            'delete',
            'disable',
            'enable',
          ],
          'classes' => [
            'table',
            'table-striped',
          ],
          'toolbar' => [
            [
              'action' => '',
              'entity' => '',
              'text' => E::ts('Add Event Template'),
              'icon' => 'fa-external-link',
              'style' => 'default',
              'target' => '',
              'join' => '',
              'path' => 'civicrm/event/add?action=add&is_template=1&reset=1',
              'task' => '',
              'condition' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
        'saved_search_id',
      ],
    ],
  ],
];
