<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;

// Temporary check can be removed when moving this file to the civi_member extension.
if (!CRM_Core_Component::isEnabled('CiviMember')) {
  return [];
}

return [
  [
    'name' => 'SavedSearch_Administer_Membership_Types',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Membership_Types',
        'label' => E::ts('Administer Membership Types'),
        'api_entity' => 'MembershipType',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'title',
            'frontend_title',
            'period_type',
            'fixed_period_start_day',
            'minimum_fee',
            'duration_unit',
            'duration_interval',
            'auto_renew',
            'relationship_type_id',
            'relationship_direction',
            'relationship_type_label',
            'max_related',
            'visibility',
            'weight',
            'is_active',
          ],
          'orderBy' => [],
          'where' => [
            ['domain_id:name', '=', 'current_domain'],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Administer_Membership_Types_SearchDisplay_Membership_Types_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Membership_Types_Table',
        'label' => E::ts('Membership Types Table 1'),
        'saved_search_id.name' => 'Administer_Membership_Types',
        'type' => 'table',
        'settings' => [
          'description' => '',
          'sort' => [
            ['weight', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'title',
              'label' => 'Membership',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'frontend_title',
              'label' => 'Frontend Title',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'period_type:label',
              'label' => 'Period',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'fixed_period_start_day',
              'label' => 'Fixed Start',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'minimum_fee',
              'dataType' => 'Money',
              'label' => 'Minimum Fee',
              'sortable' => TRUE,
              'alignment' => 'text-right',
            ],
            [
              'type' => 'field',
              'key' => 'duration_interval',
              'label' => 'Duration',
              'sortable' => TRUE,
              'rewrite' => '[duration_interval] [duration_unit:label]',
            ],
            [
              'type' => 'field',
              'key' => 'auto_renew:label',
              'label' => 'Auto-renew Option',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'relationship_type_label',
              'label' => 'Related',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'max_related',
              'label' => 'Max',
              'sortable' => TRUE,
              'alignment' => 'text-right',
            ],
            [
              'type' => 'field',
              'key' => 'visibility:label',
              'label' => 'Visibility',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'label' => 'Enabled',
              'sortable' => TRUE,
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'MembershipType',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => 'Edit',
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'MembershipType',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => 'Enable',
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => ['is_active', '=', FALSE],
                ],
                [
                  'task' => 'disable',
                  'entity' => 'MembershipType',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => 'Disable',
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => ['is_active', '=', TRUE],
                ],
                [
                  'entity' => 'MembershipType',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => 'Delete',
                  'style' => 'danger',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => ['table', 'table-striped'],
          'draggable' => 'weight',
          'cssRules' => [
            ['disabled', 'is_active', '=', FALSE],
          ],
          'toolbar' => [
            [
              'action' => 'add',
              'entity' => 'MembershipType',
              'text' => 'Add Membership Type',
              'icon' => 'fa-plus',
              'style' => 'primary',
              'target' => 'crm-popup',
              'join' => '',
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
