<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Contact_Summary_Pledges',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contact_Summary_Pledges',
        'label' => E::ts('Contact Summary Pledges'),
        'form_values' => [
          'join' => [
            'Pledge_PledgePayment_pledge_id_01' => 'Unpaid Payments',
            'Pledge_PledgePayment_pledge_id_02' => 'Paid Payments',
          ],
        ],
        'api_entity' => 'Pledge',
        'api_params' => [
          'version' => 4,
          'select' => [
            'amount',
            'SUM(Pledge_PledgePayment_pledge_id_02.actual_amount) AS SUM_Pledge_PledgePayment_pledge_id_02_actual_amount',
            'financial_type_id:label',
            'start_date',
            'GROUP_FIRST(Pledge_PledgePayment_pledge_id_01.scheduled_date ORDER BY Pledge_PledgePayment_pledge_id_01.scheduled_date ASC) AS GROUP_FIRST_Pledge_PledgePayment_pledge_id_01_scheduled_date_Pledge_PledgePayment_pledge_id_01_scheduled_date',
            'GROUP_FIRST(Pledge_PledgePayment_pledge_id_01.scheduled_amount ORDER BY Pledge_PledgePayment_pledge_id_01.scheduled_date ASC) AS GROUP_FIRST_Pledge_PledgePayment_pledge_id_01_scheduled_amount_Pledge_PledgePayment_pledge_id_01_scheduled_date',
            'status_id:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => ['id'],
          'join' => [
            [
              'PledgePayment AS Pledge_PledgePayment_pledge_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Pledge_PledgePayment_pledge_id_01.pledge_id',
              ],
              [
                'Pledge_PledgePayment_pledge_id_01.status_id:name',
                'IN',
                ['Pending', 'Overdue'],
              ],
            ],
            [
              'PledgePayment AS Pledge_PledgePayment_pledge_id_02',
              'LEFT',
              [
                'id',
                '=',
                'Pledge_PledgePayment_pledge_id_02.pledge_id',
              ],
              [
                'Pledge_PledgePayment_pledge_id_02.status_id:name',
                '=',
                '"Completed"',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contact_Summary_Pledges_SearchDisplay_Contact_Summary_Pledges_Tab',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contact_Summary_Pledges_Tab',
        'label' => E::ts('Contact Summary Pledges Tab'),
        'saved_search_id.name' => 'Contact_Summary_Pledges',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            ['start_date', 'DESC'],
          ],
          'limit' => 50,
          'pager' => [
            'hide_single' => TRUE,
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'amount',
              'label' => E::ts('Pledged'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'SUM_Pledge_PledgePayment_pledge_id_02_actual_amount',
              'label' => E::ts('Total Paid'),
              'sortable' => TRUE,
              'empty_value' => '0',
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'label' => E::ts('Financial Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => E::ts('Pledge Made'),
              'sortable' => TRUE,
              'format' => 'dateformatshortdate',
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Pledge_PledgePayment_pledge_id_01_scheduled_date_Pledge_PledgePayment_pledge_id_01_scheduled_date',
              'label' => E::ts('Next Payment'),
              'sortable' => TRUE,
              'format' => 'dateformatshortdate',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_FIRST_Pledge_PledgePayment_pledge_id_01_scheduled_amount_Pledge_PledgePayment_pledge_id_01_scheduled_date',
              'label' => E::ts('Next Amount'),
              'sortable' => TRUE,
            ],
            [
              'label' => E::ts('Payments'),
              'rewrite' => E::ts('Show Payments'),
              'alignment' => '',
              'subsearch' => [
                'filters' => [
                  [
                    'subsearch_field' => 'pledge_id',
                    'parent_field' => 'id',
                  ],
                ],
                'subsearch_mode' => 'dropdown',
                'search' => 'Contact_Summary_Pledge_Payments',
                'display' => 'Contact_Summary_Pledge_Payments_Subsearch',
              ],
              'type' => 'subsearch',
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'Pledge',
                  'action' => 'view',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('View Pledge'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'Pledge',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Update Pledge'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'pledge.cancel',
                  'entity' => 'Pledge',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-ban',
                  'text' => E::ts('Cancel Pledge'),
                  'style' => 'warning',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'Pledge',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete Pledge'),
                  'style' => 'danger',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => ['table', 'table-striped'],
          'columnMode' => 'custom',
          'toolbar' => [
            [
              'entity' => 'Pledge',
              'text' => E::ts('Add Pledge'),
              'icon' => 'fa-plus',
              'target' => 'crm-popup',
              'action' => 'add',
              'style' => 'primary',
              'join' => '',
              'path' => '',
              'task' => '',
              'conditions' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
