<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Administer_Membership_Status_Rules',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Membership_Status_Rules',
        'label' => E::ts('Administer Membership Status Rules'),
        'api_entity' => 'MembershipStatus',
        'api_params' => [
          'version' => 4,
          'select' => [
            'label',
            'is_active',
            'start_event:label',
            'start_event_adjust_interval',
            'start_event_adjust_unit:label',
            'end_event:label',
            'end_event_adjust_interval',
            'end_event_adjust_unit:label',
            'is_current_member',
            'is_admin',
            'weight',
            'is_reserved',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Administer_Membership_Status_Rules_SearchDisplay_Membership_Statuses_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Membership_Statuses_Table_1',
        'label' => E::ts('Membership Statuses Table 1'),
        'saved_search_id.name' => 'Administer_Membership_Status_Rules',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'label',
              'dataType' => 'String',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Enabled'),
              'sortable' => TRUE,
              'cssRules' => [],
            ],
            [
              'type' => 'field',
              'key' => 'start_event:label',
              'dataType' => 'String',
              'label' => E::ts('Start Event'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_event_adjust_interval',
              'dataType' => 'Integer',
              'label' => E::ts('Start Adjustment'),
              'sortable' => TRUE,
              'rewrite' => '[start_event_adjust_interval] [start_event_adjust_unit:label]',
            ],
            [
              'type' => 'field',
              'key' => 'end_event:label',
              'dataType' => 'String',
              'label' => E::ts('End Event'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_event_adjust_interval',
              'dataType' => 'Integer',
              'label' => E::ts('End Adjustment'),
              'sortable' => TRUE,
              'rewrite' => '[end_event_adjust_interval] [end_event_adjust_unit:label]',
            ],
            [
              'type' => 'field',
              'key' => 'is_current_member',
              'dataType' => 'Boolean',
              'label' => E::ts('Current Member?'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_admin',
              'dataType' => 'Boolean',
              'label' => E::ts('Administrator Only?'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_reserved',
              'dataType' => 'Boolean',
              'label' => E::ts('Is Reserved'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'path' => 'civicrm/admin/member/membershipStatus?action=update&id=[id]&reset=1',
                  'task' => '',
                  'condition' => [
                    'is_reserved',
                    '=',
                    FALSE,
                  ],
                ],
                [
                  'entity' => 'MembershipStatus',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'path' => '',
                  'task' => 'disable',
                  'condition' => [
                    'is_active',
                    '=',
                    TRUE,
                  ],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'MembershipStatus',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    FALSE,
                  ],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'MembershipStatus',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_reserved',
                    '=',
                    FALSE,
                  ],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
          'draggable' => 'weight',
          'cssRules' => [
            [
              'disabled',
              'is_active',
              '=',
              FALSE,
            ],
          ],
          'toolbar' => [
            [
              'action' => 'add',
              'entity' => 'MembershipStatus',
              'text' => E::ts('Add Membership Status'),
              'icon' => 'fa-plus',
              'style' => 'primary',
              'target' => 'crm-popup',
              'join' => '',
              'path' => '',
              'task' => '',
              'condition' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
