<?php
    return [
      [
        'name' => 'SavedSearch_Option_Values_1',
        'entity' => 'SavedSearch',
        'cleanup' => 'always',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Option_Values_1',
            'label' => 'Administer Option Values',
            'form_values' => NULL,
            'mapping_id' => NULL,
            'search_custom_id' => NULL,
            'api_entity' => 'OptionValue',
            'api_params' => [
              'version' => 4,
              'select' => [
                'id',
                'label',
                'OptionValue_OptionGroup_option_group_id_01.title',
                'OptionValue_OptionGroup_option_group_id_01.id',
                'value',
                'description',
                'is_reserved',
                'is_active',
                'OptionValue_OptionGroup_option_group_id_01.option_value_fields:label',
                'OptionValue_OptionGroup_option_group_id_01.description',
              ],
              'orderBy' => [],
              'where' => [],
              'groupBy' => [],
              'join' => [
                [
                  'OptionGroup AS OptionValue_OptionGroup_option_group_id_01',
                  'INNER',
                  [
                    'option_group_id',
                    '=',
                    'OptionValue_OptionGroup_option_group_id_01.id',
                  ],
                ],
              ],
              'having' => [],
            ],
            'expires_date' => NULL,
            'description' => NULL,
          ],
        ],
      ],
      [
        'name' => 'SavedSearch_Option_Values_1_SearchDisplay_Table',
        'entity' => 'SearchDisplay',
        'cleanup' => 'always',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Table',
            'label' => 'Table',
            'saved_search_id.name' => 'Option_Values_1',
            'type' => 'table',
            'settings' => [
              'description' => '<div class="help">
    This should be showing the group description: [OptionValue_OptionGroup_option_group_id_01.description]
    </div>',
              'sort' => [],
              'limit' => 50,
              'pager' => [],
              'placeholder' => 5,
              'columns' => [
                [
                  'type' => 'field',
                  'key' => 'label',
                  'dataType' => 'String',
                  'label' => 'Label',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'value',
                  'dataType' => 'String',
                  'label' => 'Value',
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'description',
                  'dataType' => 'Text',
                  'label' => 'Description',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'is_reserved',
                  'dataType' => 'Boolean',
                  'label' => 'Reserved?',
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'is_active',
                  'dataType' => 'Boolean',
                  'label' => 'Enabled?',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'size' => 'btn-xs',
                  'links' => [
                    [
                      'entity' => 'OptionValue',
                      'action' => 'update',
                      'join' => '',
                      'target' => 'crm-popup',
                      'icon' => 'fa-pencil',
                      'text' => 'Edit',
                      'style' => 'default',
                      'path' => '',
                      'condition' => [],
                    ],
                    [
                      'entity' => 'OptionValue',
                      'action' => 'delete',
                      'join' => '',
                      'target' => 'crm-popup',
                      'icon' => 'fa-trash',
                      'text' => 'Delete',
                      'style' => 'danger',
                      'path' => '',
                      'condition' => [],
                    ],
                  ],
                  'type' => 'buttons',
                  'alignment' => 'text-right',
                ],
                [
                  'type' => 'field',
                  'key' => 'OptionValue_OptionGroup_option_group_id_01.description',
                  'dataType' => 'Text',
                  'label' => 'Option Value Option Group: Option Group Description',
                  'sortable' => TRUE,
                  'rewrite' => '[OptionValue_OptionGroup_option_group_id_01.description]',
                ],
              ],
              'actions' => FALSE,
              'classes' => [
                'table',
                'table-striped',
              ],
              'draggable' => 'weight',
              'addButton' => [
                'path' => 'civicrm/admin/options/add?reset=1&action=add&gid=[option_group_id]',
                'text' => 'Add Option Value',
                'icon' => 'fa-plus',
              ],
              'cssRules' => [
                [
                  'disabled',
                  'is_active',
                  '=',
                  FALSE,
                ],
              ],
            ],
            'acl_bypass' => FALSE,
          ],
        ],
      ],
    ];
