<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;
return [
  [
    'name' => 'SavedSearch_Administer_Navigation_Menu',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Navigation_Menu',
        'label' => E::ts('Administer Navigation Menu'),
        'api_entity' => 'Navigation',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'label',
            'permission',
            'is_active',
            'permission_operator:label',
            'url',
          ],
          'orderBy' => [],
          'where' => [
            [
              'domain_id:name',
              '=',
              'current_domain',
            ],
            [
              'name',
              '!=',
              'Home',
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Administer_Navigation_Menu_SearchDisplay_Administer_Navigation_Menu',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Navigation_Menu',
        'label' => E::ts('Administer Navigation Menu'),
        'saved_search_id.name' => 'Administer_Navigation_Menu',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [],
          'limit' => 0,
          'pager' => FALSE,
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'label',
              'dataType' => 'String',
              'label' => E::ts('Menu Item'),
              'sortable' => TRUE,
              'icons' => [
                [
                  'field' => 'icon',
                  'side' => 'left',
                ],
              ],
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'url',
              'dataType' => 'String',
              'label' => E::ts('Url'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'path' => 'civicrm/admin/menu?action=update&id=[id]&reset=1',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'path' => 'civicrm/admin/menu?action=add&parent_id=[id]&reset=1',
                  'icon' => 'fa-folder-tree',
                  'text' => E::ts('Add subitem'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'task' => 'disable',
                  'entity' => 'Navigation',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => ['is_active', '=', TRUE],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'Navigation',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => ['is_active', '=', FALSE],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Navigation',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'hierarchical' => TRUE,
          'collapsible' => 'closed',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
