<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Price_Fields',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Price_Fields',
        'label' => E::ts('Price Fields'),
        'api_entity' => 'PriceField',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'label',
            'is_active',
            'is_required',
            'visibility_id:label',
            'active_on',
            'expire_on',
            'html_type:label',
            'COUNT(PriceField_PriceFieldValue_price_field_id_01.id) AS COUNT_PriceField_PriceFieldValue_price_field_id_01_id',
            'GROUP_CONCAT(DISTINCT PriceField_PriceFieldValue_price_field_id_01.label) AS GROUP_CONCAT_PriceField_PriceFieldValue_price_field_id_01_label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => ['id'],
          'join' => [
            [
              'PriceFieldValue AS PriceField_PriceFieldValue_price_field_id_01',
              'LEFT',
              [
                'id',
                '=',
                'PriceField_PriceFieldValue_price_field_id_01.price_field_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Price_Fields_SearchDisplay_Price_Fields',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Price_Fields',
        'label' => E::ts('Price Fields'),
        'saved_search_id.name' => 'Administer_Price_Fields',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            ['weight', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'label',
              'label' => E::ts('Label'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'html_type:label',
              'label' => E::ts('Field Type'),
              'sortable' => FALSE,
            ],
            [
              'type' => 'field',
              'key' => 'is_required',
              'label' => E::ts('Required'),
              'sortable' => FALSE,
            ],
            [
              'type' => 'field',
              'key' => 'visibility_id:label',
              'label' => E::ts('Visibility'),
              'sortable' => FALSE,
            ],
            [
              'type' => 'field',
              'key' => 'active_on',
              'label' => E::ts('Active On'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'expire_on',
              'label' => E::ts('Expire On'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'html',
              'key' => 'GROUP_CONCAT_PriceField_PriceFieldValue_price_field_id_01_label',
              'label' => E::ts('Options'),
              'sortable' => FALSE,
              'rewrite' => '{capture assign=fields}[GROUP_CONCAT_PriceField_PriceFieldValue_price_field_id_01_label]{/capture}{$fields|replace:\',\':\'<br>\'}',
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-list-alt',
                  'text' => E::ts('Options'),
                  'style' => 'default',
                  'path' => 'civicrm/admin/price/field/option#/?fid=[id]',
                  'condition' => [],
                  'task' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
            [
              'text' => E::ts(''),
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'PriceField',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Update Price Field'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'PriceField',
                  'action' => 'preview',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-eye',
                  'text' => E::ts('Preview Price Field'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'PriceField',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete Price Field'),
                  'style' => 'danger',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'draggable' => 'weight',
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
