{* file to handle db changes in 4.7.18 during upgrade *}

-- CRM-20062 New counties of Kenya.
SELECT @country_id := max(id) from civicrm_country where iso_code = "KE";
INSERT IGNORE INTO civicrm_state_province (country_id, abbreviation, name) VALUES
(@country_id, "01", "Baringo"),
(@country_id, "02", "Bomet"),
(@country_id, "03", "Bungoma"),
(@country_id, "04", "Busia"),
(@country_id, "05", "Elgeyo/Marakwet"),
(@country_id, "06", "Embu"),
(@country_id, "07", "Garissa"),
(@country_id, "08", "Homa Bay"),
(@country_id, "09", "Isiolo"),
(@country_id, "10", "Kajiado"),
(@country_id, "11", "Kakamega"),
(@country_id, "12", "Kericho"),
(@country_id, "13", "Kiambu"),
(@country_id, "14", "Kilifi"),
(@country_id, "15", "Kirinyaga"),
(@country_id, "16", "Kisii"),
(@country_id, "17", "Kisumu"),
(@country_id, "18", "Kitui"),
(@country_id, "19", "Kwale"),
(@country_id, "20", "Laikipia"),
(@country_id, "21", "Lamu"),
(@country_id, "22", "Machakos"),
(@country_id, "23", "Makueni"),
(@country_id, "24", "Mandera"),
(@country_id, "25", "Marsabit"),
(@country_id, "26", "Meru"),
(@country_id, "27", "Migori"),
(@country_id, "28", "Mombasa"),
(@country_id, "29", "Murang'a"),
(@country_id, "30", "Nairobi City"),
(@country_id, "31", "Nakuru"),
(@country_id, "32", "Nandi"),
(@country_id, "33", "Narok"),
(@country_id, "34", "Nyamira"),
(@country_id, "35", "Nyandarua"),
(@country_id, "36", "Nyeri"),
(@country_id, "37", "Samburu"),
(@country_id, "38", "Siaya"),
(@country_id, "39", "Taita/Taveta"),
(@country_id, "40", "Tana River"),
(@country_id, "41", "Tharaka-Nithi"),
(@country_id, "42", "Trans Nzoia"),
(@country_id, "43", "Turkana"),
(@country_id, "44", "Uasin Gishu"),
(@country_id, "45", "Vihiga"),
(@country_id, "46", "Wajir"),
(@country_id, "47", "West Pokot");

