<?php
use CRM_Campaign_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Administer_Campaigns',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Administer_Campaigns',
        'label' => E::ts('Administer Campaigns'),
        'api_entity' => 'Campaign',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'external_identifier',
            'title',
            'description',
            'is_active',
            'start_date',
            'end_date',
            'campaign_type_id:label',
            'status_id:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Administer_Campaigns_SearchDisplay_Campaigns_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Campaigns_Table',
        'label' => E::ts('Administer Campaigns'),
        'saved_search_id.name' => 'Administer_Campaigns',
        'type' => 'table',
        'settings' => [
          'actions' => TRUE,
          'limit' => 50,
          'classes' => ['table', 'table-striped'],
          'pager' => [
            'show_count' => FALSE,
            'expose_limit' => TRUE,
            'hide_single' => TRUE,
          ],
          'placeholder' => 5,
          'sort' => [
            ['is_active', 'DESC'],
            ['title', 'ASC'],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'title',
              'label' => 'Title',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'description',
              'label' => 'Description',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => 'Start Date',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'label' => 'End Date',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'campaign_type_id:label',
              'label' => 'Type',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => 'Status',
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'external_identifier',
              'label' => 'External ID',
              'sortable' => TRUE,
            ],
            [
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'type' => 'menu',
              'alignment' => 'text-right',
              'links' => [
                [
                  'path' => '',
                  'icon' => 'fa-pencil',
                  'text' => 'Edit',
                  'style' => 'default',
                  'condition' => [],
                  'entity' => 'Campaign',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'style' => 'default',
                  'text' => E::ts('Add Child'),
                  'icon' => 'fa-folder-tree',
                  'conditions' => [
                    [
                      'check user permission',
                      '=',
                      [
                        'manage campaign',
                      ],
                    ],
                  ],
                  'path' => 'civicrm/campaign/add?reset=1&parent_id=[id]',
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'text' => 'Enable',
                  'icon' => 'fa-toggle-on',
                  'task' => 'enable',
                  'entity' => 'Campaign',
                  'target' => 'crm-popup',
                  'join' => '',
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
                [
                  'text' => 'Disable',
                  'icon' => 'fa-toggle-off',
                  'task' => 'disable',
                  'entity' => 'Campaign',
                  'target' => 'crm-popup',
                  'join' => '',
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'Campaign',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => 'Delete',
                  'style' => 'danger small-popup',
                  'path' => '',
                  'condition' => [],
                  'task' => '',
                  'conditions' => [],
                ],
              ],
            ],
          ],
          'headerCount' => TRUE,
          'columnMode' => 'custom',
          'actions_display_mode' => 'menu',
          'toolbar' => [
            [
              'entity' => 'Campaign',
              'action' => 'add',
              'target' => 'crm-popup',
              'icon' => 'fa-plus',
              'text' => 'Add Campaign',
              'style' => 'primary',
            ],
          ],
          'cssRules' => [
            [
              'disabled',
              'is_active',
              '=',
              FALSE,
            ],
          ],
          'hierarchical' => TRUE,
          'collapsible' => 'open',
        ],
      ],
      'match' => [
        'name',
        'saved_search_id',
      ],
    ],
  ],
];
